variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql

PHPLint:PHPCS:PHP7.1:MySQL:
  image: nikschavan/docker-php:7.1
  services:
    - mysql:5.6
  script:
  # Install PHPCS and WPCS
  - composer install

  - vendor/bin/phpcs
  # - phpunit 
